AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys an Application Load Balancer (ALB) with a listeners

Parameters:
  AccountId:
    Type: String
    Default: production
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Private subnets to use for the application
  CertificateArns:
    Type: CommaDelimitedList # List<AWS::CertificateManager::Certificate::Arn>
    Description: List of ACM certificates to be used by the load balancer listener
    Default: ""

Conditions:
  HasCertificates: !Not [ !Equals [ !Join [ "", !Ref CertificateArns ], "" ] ]
  DoesNotHaveCertificates:
    Fn::Equals: [ !Join [ "", !Ref CertificateArns ], "" ]

Resources:
  PublicAlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: publicAlb
      Scheme: internet-facing
      SecurityGroups:
        - !ImportValue Ec2SecurityGroup
      Subnets: !Ref PublicSubnets
      Tags:
        - Key: Name
          Value: ec2-alb
      Type: application

  PublicAlbHttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - !If
          - DoesNotHaveCertificates
          - Type: fixed-response
            FixedResponseConfig:
              StatusCode: 200
              ContentType: text/plain
              MessageBody: "No certificates provided, no target groups were matched."
          - Type: "redirect"
            RedirectConfig:
              Protocol: "HTTPS"
              Port: 443
              Host: "#{host}"
              Path: "/#{path}"
              Query: "#{query}"
              StatusCode: "HTTP_301"
      LoadBalancerArn: !Ref PublicAlb
      Port: 80
      Protocol: HTTP

  PublicAlbHttpsListenerWithCertificates:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: HasCertificates
    Properties:
      Certificates:
        - CertificateArn: !Ref CertificateArns
      DefaultActions:
        - Type: fixed-response
      LoadBalancerArn: !Ref PublicAlb
      Port: 443
      Protocol: HTTPS

Outputs:
  PublicAlb:
    Value: !Ref PublicAlb
    Export:
      Name: PublicAlbArn
  PublicAlbCanonicalHostedZoneId:
    Value: !GetAtt PublicAlb.CanonicalHostedZoneID
  PublicAlbDnsName:
    Value: !GetAtt PublicAlb.DNSName
  PublicAlbFullName:
    Value: !GetAtt PublicAlb.LoadBalancerFullName
  PublicAlbHostname:
    Value: !Sub https://${PublicAlb.DNSName}
  PublicAlbHttpsListenerArn:
    Condition: HasCertificates
    Value: !If
      - HasCertificates
      - !Ref PublicAlbHttpsListenerWithCertificates
      - !Ref "AWS::NoValue"
    Export:
      Name: PublicAlbHttpsListenerArn
  PublicAlbHttpListenerArn:
    Value: !Ref PublicAlbHttpListener
    Export:
      Name: PublicAlbHttpListenerArn

